### ISSUE TITLE
Criar ambiente com docker

### ISSUE THREAD

**Issue by sebas5384** [TallerWebSolutions/hackathon-d8#1]
```
# Env: Development.
mysql:
  image: mysql
  # @TODO: MySQL isn't working with a volume.
  # volumes:
    # - ./volumes/mysql:/var/lib/mysql:rw
  environment:
    - MYSQL_ROOT_PASSWORD=root
    - MYSQL_USER=drupal
    - MYSQL_PASSWORD=nonroot
    - MYSQL_DATABASE=drupal

web:
  image: drupal:8.1.1-apache
  volumes:
    - ./:/var/www/html
  ports:
    - "80:80"
  links:
    - mysql:db
  environment:
    - ENV=development
```
